### ISSUE TITLE
Angular components in content page?

### ISSUE THREAD

**Issue by BobbyTable** [larscom/ng-chrome-extension#11]
Hi, 
First - Great tool and great work!

I was wondering if theres any supported scenario where im able to use angular components in the content page? For example inject a `<my-component>` in the current page DOM somewhere.

If its not supported perhaps you could have som ideas about how to achieve it. Where would i start for something like this?

**Comment by larscom** [comment]
Hi, you can't just inject a component. It needs to be bootstrapped by the angular framework. This means you need the angular framework as well the be included in that content page. 

It might be possible, somehow.. but i can't help you with that ;) 
Maybe Angular Elements is better suited for this...
