### ISSUE TITLE
Can I using contentPage to render a Angular component to Content Page?

### ISSUE THREAD

**Issue by QuanJingHong** [larscom/ng-chrome-extension#14]
I want to show some content to a Content page, Now I'm using jQuery in contentPage.ts. But I don't want to handle dom manualy.  Can I render Angular component  to Content page?

**Comment by chan-dev** [comment]
@QuanJingHong have you found a solution for this without using jQuery?

**Comment by QuanJingHong** [comment]
> @QuanJingHong have you found a solution for this without using jQuery?

I haven't found a solution yet? and you?

**Comment by chan-dev** [comment]
As far as i know, there's no straightforward way to do this, but one way is to specify the built angular files under content scripts in manifest.json.

Something like this:
```
  "content_scripts": [
    {
      "matches": ["http://*/*", "https://*/*"],
      "js": [
        "contentPage.js",
        "polyfills.js",
        "polyfill-webcomp.js",
        "runtime.js",
        "main.js"
      ],
      "css": ["styles.css"],
      "run_at": "document_idle"
    }
  ],
```

Then you have to find a way to put the compiled angular files in the same directory as the manifest.json using webpack or any build tool.
