### ISSUE TITLE
Some thing doesn't work with Angular Material

### ISSUE THREAD

**Issue by QuanJingHong** [larscom/ng-chrome-extension#15]
I have tried some thing with Material, some thing doesn't work. 

1. Can't close Dialog
2. Can't Toggle a side nav

https://stackoverflow.com/questions/67856612/mat-dialog-close-doesnt-work-on-angular-11-meterial-11/67856726#67856726

**Comment by larscom** [comment]
Hi, this is not related to this tool. This is angular specific.
