### ISSUE TITLE
Error: authentication required but no callback set

### ISSUE THREAD

**Issue by chan-dev** [larscom/ng-chrome-extension#16]
I've installed the tool but executing it throws an error. 
My nodejs version is v12.22.1
![ng-chrome-issue](https://user-images.githubusercontent.com/46891115/126055537-e2429daa-ba13-4ed7-ace7-eeeff64a9ae5.png)

**Comment by larscom** [comment]
Hi, do you still have this issue?
I can't reproduce with version 12.22.1 of node.

What is your OS?

**Comment by chan-dev** [comment]
Yup, I still having the issue. I'm on Xubuntu 20.04

**Comment by larscom** [comment]
can you try update @larscom/ng-chrome-extension to v2.0.4 and see if it works.

**Comment by chan-dev** [comment]
tried updating and reinstalling but still the problem persists

**Comment by larscom** [comment]
Do you get the same error when you clone any open source project from github? Like the tool itself? (git clone https://github.com/larscom/ng-chrome-extension.git)

**Comment by chan-dev** [comment]
do you mean just the **git clone** action itself? If so, no i don't get any error

**Comment by larscom** [comment]
Have you managed to find the problem? Else ill close this issue
