### ISSUE TITLE
Import primeng

### ISSUE THREAD

**Issue by zornic84** [larscom/ng-chrome-extension#22]
Hi,

I am programming a small internal extension and have imported primeng. When I now run the project with "npm start", the controls are all displayed cleanly. But when I run the command "npm run build:production" and import the version, it seems that the css files are not copied. What do I have to add so that everything is taken over by primeng?

angular.json
`"styles": [
"node_modules/primeng/resources/themes/saga-blue/theme.css",
"node_modules/primeng/resources/primeng.min.css",
"node_modules/primeicons/primeicons.css",
"node_modules/primeflex/primeflex.css",
"angular/src/styles.scss"
],`

package.json
`
"dependencies": {
    "@angular/animations": "^13.0.2",
    "@angular/cdk": "^13.0.2",
    "@angular/common": "^13.0.2",
    "@angular/compiler": "^13.0.2",
    "@angular/core": "^13.0.2",
    "@angular/forms": "^13.0.2",
    "@angular/material": "^13.0.2",
    "@angular/platform-browser": "^13.0.2",
    "@angular/platform-browser-dynamic": "^13.0.2",
    "@angular/router": "^13.0.2",
    "crypto-js": "^4.1.1",
    "ngx-build-plus": "^12.2.0",
    "primeflex": "^3.1.2",
    "primeicons": "^5.0.0",
    "primeng": "^13.1.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^13.0.3",
    "@angular/cli": "^13.0.3",
    "@angular/compiler-cli": "^13.0.2",
    "@angular/language-service": "^13.0.2",
    "@types/chrome": "0.0.141",
    "@types/node": "^12.12.32",
    "awesome-typescript-loader": "^5.2.1",
    "bestzip": "^2.1.7",
    "npm-run-all": "^4.1.5",
    "rimraf": "^2.7.1",
    "ts-loader": "^9.2.6",
    "ts-node": "~10.3.0",
    "typescript": "~4.4.4",
    "webpack-cli": "^4.9.0"
  }
`

Many greetings

**Comment by larscom** [comment]
Hi, thanks for reporting.

You can fix it yourself by editing "angular.json" in your project. 
inlineCritical needs to be false

See this commit: https://github.com/larscom/angular-chrome-extension/commit/24fc40c7f84d28e27cc18db6ebc58999bdc374c7


You may also generate a new extension with "ng-chrome" and it will also work.
