### ISSUE TITLE
I always get an error when I create a project with a "-" in the project name

### ISSUE THREAD

**Issue by duanluan** [larscom/ng-chrome-extension#23]
![image](https://user-images.githubusercontent.com/14957667/151847951-763356d3-8054-4259-b138-a56dc3709ad0.png)

I always get an error when I create a project with "-" in the project name, and there are no files generated in the folder from the beginning, and vice versa.

**Comment by larscom** [comment]
Hi, which version of the app are you using and which version of node/npm?

**Comment by duanluan** [comment]
> Hi, which version of the app are you using and which version of node/npm?

node: v14.17.1 & npm: 6.14.13

**Comment by larscom** [comment]
What is the output of: ng-chrome -version

**Comment by duanluan** [comment]
> What is the output of: ng-chrome -version

2.1.2

**Comment by larscom** [comment]
Try updating to 2.1.3 and see if it works. 

Although i think its network related. I have tried it on Windows as well with the same versions as you and it works as expected.

Maybe try a different network? Or disable firewalls

**Comment by larscom** [comment]
Closed due to inactivity. If you still get this issue you can open a new ticket.
