### ISSUE TITLE
Unable to add css urls and fonts in angular.json

### ISSUE THREAD

**Issue by maddybin** [larscom/ng-chrome-extension#28]
I am trying to add CSS themes for primeNg library. 
With a normal angular project we can do it by adding the path to `angular.json` >> styles.
I am not able to do in angular extension as it throws me an error.

`Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline'....`

Please suggest me how to use those fonts and styles. Thank you @larscom

**Comment by maddybin** [comment]
@larscom Can you please replay over it

**Comment by larscom** [comment]
Hi, 

i just followed the guide on prime-ng and it just works: https://www.primefaces.org/primeng/setup

![Screenshot_20220801_201014](https://user-images.githubusercontent.com/1215195/182213957-928701e7-d8be-4aa4-a9df-3cdad256895a.png)

In the root direct do:

```
npm install primeng --save

npm install primeicons --save
```

Add the following to `angular.json`

![Screenshot_20220801_201301](https://user-images.githubusercontent.com/1215195/182214347-cf76588d-392e-4c5f-b9da-81ae9f81c083.png)

```
            "styles": [
              "node_modules/primeng/resources/themes/lara-light-blue/theme.css",
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/primeicons/primeicons.css",
              "angular/src/styles.scss"
            ]
```

Add `ButtonModule` to `popup.module.ts` imports

And lastly, add a button to `popup.component.html`

`<button pButton pRipple type="button" label="Primary" class="p-button-raised"></button>`


(i did create a new project with `ng-chrome`)

**Comment by maddybin** [comment]
I think it was an issue with the Angular 12 upgrade. It's working fine with Ng 14 upgrade.  Thanks for the Help @larscom #Kudos.
