### ISSUE TITLE
Using the extension as addition to existing web page

### ISSUE THREAD

**Issue by devcpattern** [larscom/ng-chrome-extension#30]
I have tries the extension and it did work on opening new tab.
My question is about using that a bit differently:
The extension should connect to specific url (manifest) and then inject the entire angular (ver 9) as a floating div into the existing DOM
(btw the dom is also made from angular, though 12)

Can this be achieved?

**Comment by larscom** [comment]
no idea tbh, don't think its possible, might give security issues.
