### ISSUE TITLE
npm start not running on any port

### ISSUE THREAD

**Issue by prosenjeet123** [larscom/ng-chrome-extension#32]
I tried running the npm start but not able to see it running on any port. Yes the changes reflect on chrome://extension but not able to live preview it as it does with ng serve

**Comment by larscom** [comment]
Because this app is dependend on the 'chrome' namespace...

You can run it without, but you need to make modifications to make it work.

1. edit `main.ts`

**main.ts**
```
if (environment.production) {
  enableProdMode();
}

if (chrome.tabs) {
  chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
    const { id: tabId } = [...tabs].pop();

    // provides the current Tab ID so you can send messages to the content page
    platformBrowserDynamic([{ provide: TAB_ID, useValue: tabId }])
      .bootstrapModule(AppModule)
      .catch((error) => console.error(error));
  });
} else {
  platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch((error) => console.error(error));
}
```


2. add the following to the `app-routing.module.ts` routes array:

```
 {
    path: '**',
    redirectTo: 'tab'
  }
```

3. run `npm run ng -- serve`
