### ISSUE TITLE
Build scripts ->  "ng build --configuration='development'"

### ISSUE THREAD

**Issue by Robinyo** [larscom/ng-chrome-extension#34]
In the generated `package.json`:

```
  "scripts": {

    ...

    "build:angular": "ng build --configuration development",
    "build:angular-production": "ng build --configuration production",

    ...

  },
```

Should be:

```
  "scripts": {
    ...

    "build:angular": "ng build --configuration='development'",
    "build:angular-production": "ng build --configuration='production'",

    ...

  },
```

**Comment by larscom** [comment]
I think it's fine, try to create a new angular project and you'll see that it is also without the `=`

```shell
ng new myproject
```


![Screenshot_20221123_204502](https://user-images.githubusercontent.com/1215195/203633704-812fd87b-5690-490e-
b5e1-67602c331ec4.png)

https://angular.io/guide/workspace-config#alternate-build-configurations

**Comment by Robinyo** [comment]
Ok, so that is unexpected.

I had to update the `package.json`(as above) to get it to work correctly:

```
npm run build
````

I only noticed this issue as I was updating my console logger service (to work with a browser extension) and couldn't figure out why it wasn't working.

console-logger.service.ts:

```
...

const noop = (): any => undefined;

@Injectable({
  providedIn: 'root'
})
export class ConsoleLoggerService implements Logger {

  get info() {

    if (isDebugMode) {
      return partial(chrome.runtime.sendMessage);
    } else {
      return noop;
    }

  }

}

function partial(func, ...argsBound) {
  return function(...args) { // (*)
    return func.call(this, ...argsBound, ...args);
  }
}
```

serviceWorker.js:

```
console.log('serviceWorker script loaded');

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log(request);
})

```

![Screen Shot 2022-11-24 at 07 04 37](https://user-images.githubusercontent.com/12203540/203636836-e9b804d0-6376-4753-b9c8-146860d40f01.png)

![Screen Shot 2022-11-24 at 07 04 49](https://user-images.githubusercontent.com/12203540/203636857-4a2e1598-8e3e-4a8b-869e-91c448feddfc.png)

**Comment by Robinyo** [comment]
Sorry, my bad, I was typing:

```
ng build
```

Rather than:

```
npm run build
```

**Comment by larscom** [comment]
Good! :-)
