### ISSUE TITLE
how to load script like jquery.min.js into serviceWorker.ts

### ISSUE THREAD

**Issue by tanldt** [larscom/ng-chrome-extension#37]
Got stuck to do on how to load script like jquery.min.js into serviceWorker.ts
any suggestion?
Thanks

**Comment by larscom** [comment]
if you use the latest version of this cli tool (3.1.0+) you can change directory into the 'chrome' folder and install the deps:

```
npm install jquery
npm install --save-dev @types/jquery
```

It should work
