### ISSUE TITLE
Unable to Import ReactiveFormsModule

### ISSUE THREAD

**Issue by maddybin** [larscom/ng-chrome-extension#42]
imports: [RouterOutlet, CommonModule, ReactiveFormsModule, FormsModule ]

```
./node_modules/@angular/forms/fesm2022/forms.mjs:5885:14-34 - Error: export 'ɵɵInputFlags' (imported as 'i0') was not found in '@angular/core' (possible exports: ANIMATION_MODULE_TYPE, APP_BOOTSTRAP_LISTENER, APP_ID, APP_INITIALIZER

```

**Comment by larscom** [comment]
This works perfectly fine, build is successfull. 
What is your node version, i think you need at least node 18.

![image](https://github.com/user-attachments/assets/9a45c47f-bc4a-483d-a2d6-b1a2ceb0c4d2)
