### ISSUE TITLE
How to use npm bundles in contentScript ?

### ISSUE THREAD

**Issue by Dhan3777** [larscom/ng-chrome-extension#43]
I am trying to use tippy.js. I have. installed it using npm. I am able to import from node_modules into contentPage.js.
Issue is when I try to use it inside browser it gives error contentPage.js:2082 Uncaught ReferenceError: process is not defined
`  if (process.env.NODE_ENV !== "production") {
    resetVisitedMessages();
  }`

Also I am not able to use latest angular syntax like @if
and importing FormsModule or reactiveFormsModule fails the serve and build process. Says "angular export not found error in form module"

@larscom

**Comment by larscom** [comment]
process is not available in the browser, only in a node runtime.

You **can** use `@if` but you need to import the `CommonModule` from `@angular/common`

```ts
@Component({
  selector: 'app-tab',
  standalone: true,
  imports: [CommonModule], <---------------
  templateUrl: 'tab.component.html',
  styleUrls: ['tab.component.scss']
})
```

This is basic angular stuff. This is not the place to ask how angular works.
