### ISSUE TITLE
How to add analytics (e.g. Google Analytics, App Insights)

### ISSUE THREAD

**Issue by FSou1** [larscom/ng-chrome-extension#6]
Hi Lars,

Thank you for this repo, I've been using it for developing my chrome extension. The repo is such an awesome way to simplify the starting point, it is just extremely helpful. 

Currently, I'm looking for a clear way to add Google Analytics script to both chrome and angular sides. Do you have any thoughts or plans on that?

Thank you in advance.

**Comment by larscom** [comment]
Hi,

You can add any analytics module to the angular side. For example: https://github.com/angulartics/angulartics2
There you can handle pretty much any event you want. 

Don't know if its possible to add it on the chrome side, besides that, don't think you need it there either?

Good luck 👍

**Comment by FSou1** [comment]
Oh, thx for the link, will take a look.

I have successfully added the GA to the Chrome side so far. It has been a matter of:
* Adding a separate javascript file with a snippet (it is important since Chrome runtime does not allow to execute inline scripts without some mambo-jumbo policies);
* Importing this file to the background page (and a content script should send a message to the background page if there is a need to track something).

The reason I'd like to track the chrome side of the extensions is because of some content scripts. So the angular side is more about interacting with UI (e.g. popup, options), and the chrome side is helpful to catch hotkeys, runtime.messages, e.t.c.

References:
* https://stackoverflow.com/questions/11372107/content-script-tracking-with-google-analytics/31654055#31654055
* https://developers.google.com/analytics/devguides/collection/analyticsjs/tracking-snippet-reference

**Comment by larscom** [comment]
All right, glad that it worked out :-)
